quarkus.http.test-port=${quarkus.http.port}
quarkus.http.test-ssl-port=${quarkus.http.ssl-port}

# quarkus.rest-client.hello.url=http://localhost:8080
quarkus.rest-client.hello.url=https://localhost:8443
quarkus.http.insecure-requests=disabled

quarkus.tls.key-store.p12.path=.certs/my-cert-keystore.p12
quarkus.tls.key-store.p12.password=password

%new.quarkus.tls.cli-conf.trust-store.p12.path=.certs/my-cert-truststore.p12
%new.quarkus.tls.cli-conf.trust-store.p12.password=password
%new.quarkus.rest-client.hello.tls-configuration-name=cli-conf

%dflt.quarkus.tls.trust-store.p12.path=.certs/my-cert-truststore.p12
%dflt.quarkus.tls.trust-store.p12.password=password

%old.quarkus.rest-client.hello.trust-store=.certs/my-cert-truststore.p12
%old.quarkus.rest-client.hello.trust-store-password=password

